paths:
  output_dir: "output"
  raw_dir: "output/raw"
  interim_dir: "output/interim"
  processed_dir: "output/processed"

http:
  connect_timeout_sec: 3
  read_timeout_sec: 12
  max_retries: 5
  backoff_base_sec: 0.8

sources:
  odcloud:
    base: "https://api.odcloud.kr/api"
    path: "/15056087/v1/uddi:3bcca607-8b03-4760-b1df-abc5d4ef2a36"
    per_page: 500

  kto:
    base: "http://apis.data.go.kr/B551011/TatsCnctrRateService"
    path: "/tatsCnctrRatedList"
    mobile_os: "WIN"
    mobile_app: "Yeogigangwon"
    signgu_codes:
      "51":
        - "51110"  # 춘천시
        - "51130"  # 원주시
        - "51150"  # 강릉시
        - "51170"  # 동해시
        - "51190"  # 태백시
        - "51210"  # 속초시
        - "51230"  # 삼척시
        - "51720"  # 홍천군
        - "51730"  # 횡성군
        - "51750"  # 영월군
        - "51760"  # 평창군
        - "51770"  # 정선군
        - "51780"  # 철원군
        - "51790"  # 화천군
        - "51800"  # 양구군
        - "51810"  # 인제군
        - "51820"  # 고성군
        - "51830"  # 양양군

  kma:
    base: "http://apis.data.go.kr/1360000/AsosDalyInfoService"
    path: "/getWthrDataList"
    data_type: "JSON"
    data_cd: "ASOS"
    date_cd: "DAY"

features:
  # 시간 피처 버킷 정의
  peak_hours: [10, 11, 12, 13, 14, 15, 16]  # 예시: 10~16시 피크
